Ext.define("Admin.view.issuemanagement.views.forms.AddActionPlanForm", {
  extend: "Ext.form.Panel",
  xtype: "addactionplanform",
  controller: "issuemanagementvctr",
  autoScroll: true,
  scrollable: true,
  bodyPadding: 8,
  defaults: {
    labelAlign: "top",
    allowBlank: false,
  },
  viewModel: {
    type: "",
  },
  layout: {
    type: "column",
  },
  bodyPadding: 5,
  defaults: {
    columnWidth: 0.33,
    margin: 5,
    labelAlign: "top",
  },
  bodyPadding: 8,
  items: [
    {
      xtype: "hiddenfield",
      margin: "0 20 20 0",
      name: "_token",
      value: token,
      allowBlank: true,
    },
    {
      xtype: "hiddenfield",
      fieldLabel: "id",
      margin: "0 20 20 0",
      name: "id",
      allowBlank: true,
    },
    {
      xtype: "fieldset",
      columnWidth: 1,
      // title: "Create",
      collapsible: false,
      defaults: {
        labelAlign: "top",
        allowBlank: false,
        labelAlign: "top",
        margin: 5,
        xtype: "textfield",
        allowBlank: false,
        columnWidth: 1,
      },
      layout: "column",
      items: [
        {
          xtype: "textarea",
          fieldLabel: "Action",
          margin: "0 20 20 0",
          name: "action",
          columnWidth: 1,
          allowBlank: false,
        },
        {
          xtype: "textfield",
          fieldLabel: "Responsible Person",
          margin: "0 20 20 0",
          name: "responsible_person",
          columnWidth: 0.33,
          allowBlank: true,
        },
        {
          xtype: "datefield",
          fieldLabel: "Start Date",
          margin: "0 20 20 0",
          name: "start_date",
          columnWidth: 0.33,
          allowBlank: false,
        },
        {
          xtype: "datefield",
          fieldLabel: "Completion Date",
          margin: "0 20 20 0",
          name: "completion_date",
          columnWidth: 0.33,
          allowBlank: true,
        },
      ],
    },
  ],
  dockedItems: [
    {
      xtype: "toolbar",
      ui: "footer",
      dock: "bottom",
      items: [
        "->",
        {
          text: "Save Details",
          iconCls: "x-fa fa-save",
          action: "save",
          name: "save_action_plan_btn",
          storeID: "issuemanagementactionplanstr",
          formBind: true,
          ui: "soft-blue",
          action_url: "issuemanagement/issue_action_plans",
        },
      ],
    },
  ],
});
